### ISSUE TITLE
Create datatypes for the game state

### ISSUE THREAD

**Issue by aidandenlinger** [aidandenlinger/kings-in-the-corner#3]
Create an object to hold game state. Would entail objects like Cards, piles of cards, current player, etc. Holds everything that needs to be known and/or rendered by the game. How are cards represented? How are we representing each of the 8 piles? How are we representing the deck each player is holding? What card or pile is the player currently looking at? Try not to hardcode 2 players, so that extending it to 4 players isn’t miserable.

Once all the objects are created, can start working on basic utility functions (ex, shuffle function to return a permutation of a deck of cards, initalize a game state object, etc)

**Comment by aidandenlinger** [comment]
<https://github.com/ambuc/solitaire/blob/master/src/CardTypes.hs> seems like a good resource

**Comment by sharanmayank** [comment]
Developed
